### PR TITLE
Grammar fixes in the manpage

### PR DESCRIPTION
**Pull request by pskocik**

### CODE REVIEW

**Comment by pskocik** [comment]
It's not perfect, but it hopefully makes the docs a little bit more readable. It's cross-referenced with the gh-pages-gen branch via comments.

**Comment by skvadrik** [comment]
Look quite perfect for me. ;)
Thanks again!

**Comment by skvadrik** [comment]
I really appreciate your fix; my wording is sometimes terrible.

**Comment by pskocik** [comment]
Glad it's well received. It's possible I'll make another PR that fixes this one. It's quite likely there's still some minor issues, some of which I probably introduced myself (overall I believe this patch is an improvement, though).

**Comment by skvadrik** [comment]
It definitely is. When writing docs, I often spend a lot of time thinking over some phrase and end up not seeing obvious mistakes in it.

**Pull request merged**
